# Page settings

baseurl = "https://whisperd.tech/resume/"
languageCode = "en-us"
title = "Kaichao Sun Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-128168145-1"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Resume of Kaichao Sun"
    author = "Kaichao Sun"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Kaichao Sun"
        tagline = "Software Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: kaichaosuna@gmail.com"
        title = "kaichaosuna@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+86 15229295896"
        title = "+86 15229295896"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//whisperd.tech"
        title = "whipserd.tech"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/kaichao-sun-b1845aa0/"
        title = "in/kaichao-sun"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/dashengSun"
        title = "github.com/dashengSun"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/kaichaosun"
        title = "@kaichaosun"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Master of Engineering"
        college = "Northwestern Polytechnical University"
        dates = "2012 - 2015"

        [[params.education.list]]
        degree = "Bachelor's degree"
        college = "Northwestern Polytechnical University"
        dates = "2008 - 2012"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Chinese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Reading"

        [[params.interests.list]]
        interest = "Ping pong"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**As a Blockchain / DLT Developer,** I have comprehensive technical skill set and expertise around **Substrate, Solidity, IPFS, WASM**. Now I'm interested in learning more about **Holochain and mutual credits**. \n\nI have been working as a Backend Developer of Web 2.0, masters the skill like web development, microservice design, functional programming, CI/CD, cloud computing, TDD, etc. \n\nI enjoy working in an agile team. Remote work is another lifestyle which makes me comfortable. Currently, I'm focusing on broad Distributed Ledger Technology. Coding in the night/quiet makes me feel great."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Developer Advocate"
        dates = "Jul 2019 - Present"
        company = "Parity Technologies, Remote"
        details = "**Fully work on a decentralized world,** I design initiatives to promote Substrate to developers includes, a writing column with monthly tech writeup, design the online course outline and record parts of the videos, we have trained more than 800 devs. Also participates in the Web3 Bootcamp and Web3 Forum as technical director. \n\nOpen source contribution includes, runtime modules for beginners, a template to start a Proof of Stake blockchain, authorized node participation to compose a permissioned blockchain, etc"

        [[params.jobs.list]]
        position = "Consultant"
        dates = "Jul 2016 - Jun 2019"
        company = "ThoughtWorks, Xi'an"
        details = "**As a Full Stack Developer,** I have been working for the client REA Group (a global online real estate advertising company) for more than two years. During this period, I work closely with a great full functional team (includes PM, BA, etc) to deliver many great products like Audience Maximiser, Flexi subscriptions, etc. These products bring lots of value to the company. Also I have participated a few HackDay projects, these projects are focus on re-imagine business model and improve daily workflow. \n\nWork includes, <li>Design microservices based on domain knowledge, product requirement and team structure. <li>Master Functional Programming to do backend development for each microservice. <li>Using React.js, Vue.js to create the web page. <li>TDD experiences in Scala, Ruby, Java, Golang, NodeJS. <li>Doing CI/CD by leveraging Docker, Buildkite / Bamboo. <li>Master the widely used infrastructure like AWS, k8s, Splunk, NewRelic, PagerDuty, JIRA, Git. <li>Sharing knowledge in community and team. <li>Develope others like new ones, and review candidates’ homework."

        [[params.jobs.list]]
        position = "Developer"
        dates = "Apr 2015 - Jul 2016"
        company = "Quyi, Xi'an"
        details = "**I start my career** in Quyi which is startup company focus on mobile healthcare. This is so excited, almost everything is different and new. I become a quick learner to understand enough business context, surf the internet to learn technology day and night, organise meetings for projects. Details include: <br /><li>Break the original monolithic architecture into microservices. <li>Develop open platform with SpringMVC for third-party application to access the services. <li>Develop service register and discovery with Zookeeper. <li>Design API Gateway with Netty. <li>Do performance test with JMeter. <li>Provide technical support for third-party."


    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**Following are side projects or open source libraries that I usually work on.** "

        [[params.projects.list]]
        title = "Start FP in Scala"
        url = "https://github.com/dashengSun/start-FP-in-scala"
        tagline = "A functional programming tutorial in Scala."

		[[params.projects.list]]
        title = "Substrate"
        url = "https://github.com/paritytech/substrate"
        tagline = "A framework to build blockchain. I have been actively contribute to its source code."

        [[params.projects.list]]
        title = "Substrate Stencil"
        url = "https://github.com/kaichaosun/substrate-stencil"
        tagline = "A template for kick starting a Substrate based PoS chain."

        [[params.projects.list]]
        title = "Play Substrate"
        url = "https://github.com/kaichaosun/play-substrate"
        tagline = "Runtime modules for beginners to play with."

        [[params.projects.list]]
        title = "Substrate Course Primer & Advanced"
        url = "https://github.com/SubstrateCourse/slides/blob/master/outline.md#substrate-blockchain-application-development"
        tagline = "Cohort based online course for developers."

        [[params.projects.list]]
        title = "Substrate Blockchain Development Column"
        url = "https://zhuanlan.zhihu.com/substrate"
        tagline = "Tech writings for blockchain and Substrate."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "DLT"
        level = "90%"

        [[params.skills.list]]
        skill = "Rust"
        level = "80%"

        [[params.skills.list]]
        skill = "Substrate"
        level = "90%"

        [[params.skills.list]]
        skill = "Solidity"
        level = "70%"

        [[params.skills.list]]
        skill = "Holochain"
        level = "60%"

        [[params.skills.list]]
        skill = "Scala"
        level = "80%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "90%"

        [[params.skills.list]]
        skill = "Javascript & ReactJS"
        level = "80%"

        [[params.skills.list]]
        skill = "AWS"
        level = "80%"

        [[params.skills.list]]
        skill = "Docker & Kubernetes"
        level = "85%"

        [[params.skills.list]]
        skill = "Golang"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
